#!/bin/bash
echo "Running frontend lint before commit..."

# Go to the subfolder
cd src/web || exit 1

# Run your command
yarn lint
status=$?

# Go back to repo root
cd ../..

# Abort commit if the command failed
if [ $status -ne 0 ]; then
  echo "Lint failed. Commit aborted."
  exit 1
fi

echo "Lint passed. Continuing with commit."